# Generated by Django 2.0.5 on 2018-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('big_ope', models.FloatField()),
                ('big_con', models.FloatField()),
                ('big_ext', models.FloatField()),
                ('big_agr', models.FloatField()),
                ('big_neu', models.FloatField()),
            ],
        ),
    ]
